### ISSUE TITLE
New Tongwentang doesn't work in Firefox Developer Edition 42

### ISSUE THREAD

**Issue by pei-lun** [softcup/New-Tongwentang-for-Firefox#1]
I think it is caused by E10s enabled by default.

**Comment by softcup** [comment]
New version and support firefox 50+
https://addons.mozilla.org/zh-TW/firefox/addon/new_tongwentang/

**Comment by yfdyh000** [comment]
@softcup [项目](https://github.com/softcup/New-Tongwentang-for-Firefox)的网址栏（`http://tongwen.openfoundry.org/`）该更新了吧。
放网址时去掉`zh-TW`，使其自动检测和跳转。
