### ISSUE TITLE
剪貼簿轉碼

### ISSUE THREAD

**Issue by panweihwa** [softcup/New-Tongwentang-for-Firefox#18]
同文堂裏面最好的一個功能是剪貼簿轉碼。希望那個功能可以恢復。

**Comment by softcup** [comment]
如果沒有意外的話，這個功能將在 Firefox 54 版開始支援。

**Comment by SyaoranChang** [comment]
你好，
目前 右鍵 剪貼簿: 轉 繁體 這個功能
似乎只有對複製 "瀏覽器中" 的文字 才有用
如果從筆記本中複製文字似乎沒有作用
請問這個可能改成跟舊版的一樣都會轉繁體嗎?

借文章請問一下
請問有機會增加 舊版本的自訂模式內 剪貼簿的文字轉繁體 的小按鈕嗎?
希望可以增加這個功能
也是希望從筆記本中複製文字也會轉繁體

**Comment by t7yang** [comment]
@SyaoranChang 
目前用 55 穩定版測試，在 win 和 mac 環境下已經沒有這個現象。請協助確認，若已沒有這個現象，議題將被關閉。

**Comment by SyaoranChang** [comment]
Firefox 55.0.3
新同文堂 1.5
從筆記本中複製文字 用 右鍵 剪貼簿: 轉 繁體 
有正常轉 繁體了
