### ISSUE TITLE
1.1 版在 addons.mozilla.org 上各頁面都無效

### ISSUE THREAD

**Issue by irvin** [softcup/New-Tongwentang-for-Firefox#3]
例如 https://addons.mozilla.org/zh-TW/firefox/
右鍵選單會出來，但是選擇轉換時無效

其他網頁都正常

**Comment by softcup** [comment]
經過測試，發現在 addons.mozilla.org 底下，同文堂相關的 JS 並沒有被載入。
這有可能是 WebExtensions 禁止在 addons.mozilla.org 網域內載入 Extension，在 developer.mozilla.org 就有正常被載入。

**Comment by ettoolong** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1310082
因為不希望你透過 content script 去修改 AMO 的頁面(可能造成安全性問題)
同樣的, Chrome 也禁止他們家的套件在 chrome store 上生效.
所以這條 issue 應該可以關了.
