### ISSUE TITLE
請求新增訂閱功能！ 

### ISSUE THREAD

**Issue by zhtw2013** [softcup/New-Tongwentang-for-Firefox#34]
ex.我在Github上維護一份用詞清單
使用了訂閱功能後，只要Github上的清單更新了，
本機的同文堂也自動更新詞彙轉換清單。

像終結內容農場一樣，可自動訂閱規則，檢查更新！

![default](https://user-images.githubusercontent.com/9501406/34600809-50e3ee7c-f234-11e7-86e4-3ff5021c7d15.png)

**Comment by t7yang** [comment]
內部討論已經有提到訂閱機制了，只是什麼時候可以實作出來是個大問題。

**Comment by zhtw2013** [comment]
瞭解，感謝你！

**Comment by t7yang** [comment]
https://github.com/tongwentang/New-Tongwentang-for-Firefox/tree/develop
因為master還沒合併最新的develop分支，所以要切換過去才看得到一些新增待辦

ps. 是不需要關閉這個issue啦，這樣開發者們比較有壓力（笑
