### ISSUE TITLE
啟用《為什麼你們就是不能加個空格呢？》腳本後，漢譯外國人姓名常常無法順利轉換

### ISSUE THREAD

**Issue by kerokeroro** [softcup/New-Tongwentang-for-Firefox#36]
你好
我很高興能使用新版同文堂套件帶來的便利性
但是最近遇到一些問題如下：

漢譯外國人姓氏跟名字時，通常會加入間隔號「·」
例如唐納‧川普、巴拉克‧歐巴馬等

但是當我安裝《為什麼你們就是不能加個空格呢？》腳本後
網頁文章會先在中英文、標點符號前插入空格
造成新同文堂套件就無法辨識那些我設定好要轉換的外國譯名

請問有辦法再下一版本的新同文堂套件做更新
讓程式可以無視「像間隔號這類特定標點符號」跟中文字間的空格，一併轉換嗎??

**Comment by t7yang** [comment]
@kerokeroro 
這個問題有兩個面向要可以討論：

1. 執行順序問題
除非可以保證新同堂可以在該指令碼執行前執行否則就無法測底解決這個問題，但就算要解決執行順序的問題也必須是雙方互相配合（透過套件的機制），這通常很難辦到。未來新同文堂會考慮新增全域的事件廣播，但也要對方配合才可以。

2. 空格跟符號也是比對的目標
所以理論上無法「無視」空格跟符號的存在。

建議：
自己去那個 script 裡面加一段等待網頁執行完畢並延後處理的程式碼可能會比較快可以解決你現在問題。
