### ISSUE TITLE
在部分網站圖示轉換失效

### ISSUE THREAD

**Issue by R-wild** [softcup/New-Tongwentang-for-Firefox#37]
http://scp-wiki-cn.wikidot.com/grant-request-for-the-manufacture-of-devices-to-regulate
如標題，上述網址在若點擊圖示不會有反應，但若使用右鍵選單便可順利轉換

此外，新同文堂似乎與Dark Mode這個附加元件衝突
https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/
若安裝Dark Mode後圖示轉換功能一樣會失靈

(當然，第一個網址是在無安裝dark mode的狀況下測試的)

Firefox Nightly 60.0a1

**Comment by t7yang** [comment]
@R-wild 
問題一：
圖示轉換的設定是什麼？如果是自動轉換的話，有可能會發生辨識錯誤的情況（這部分是內建API的問題，不是套件可以解決的）。

問題二：
用新設定檔的情況下沒有發現問題，請明確寫出重現問題步驟。

所有套件都一樣，不可能要求在 nightly 下可以 100% 正常運作。
