### ISSUE TITLE
Html title 似乎不會被轉換

### ISSUE THREAD

**Issue by willyyoung** [softcup/New-Tongwentang-for-Firefox#46]
分頁標題，也就是 html title 似乎不會被簡繁轉換到，在加入書籤時挺困擾的，因為得刻意切換到簡體(or繁體)才能進行搜索，變成得簡繁各找一次。

比較奇怪的是，分頁標題有時會有「簡體→正體→變回簡體」的現象，不太確定是什麼原因，在比較慢的電腦上特別明顯。

**Comment by t7yang** [comment]
從原始碼的行為，網頁的標題確實是會被轉換的。請明確給出重複實現問題的步驟。

「簡體→正體→變回簡體」一樣請給出重現問題的步驟，如果瀏覽的網頁是屬於 SPA 單頁式網頁是有可能的，因為標題有可能被動態切換。

**Comment by willyyoung** [comment]
> 「簡體→正體→變回簡體」一樣請給出重現問題的步驟，如果瀏覽的網頁是屬於 SPA 單頁式網頁是有可能的，因為標題有可能被動態切換。

找了很久終於找到問題在哪，會導致分頁標題改回來的原因還滿多個，不過最主要的原因是因為「Tab Mix - Rename Tab」這個擴充套件，他有個根據網址修改分頁名稱的選項，不過不管有沒有勾選，造成的行為都跟想像中有落差，Console那邊也是一堆訊息，感覺應該要大修。

平台：Windows 7 x64
Firefox版本：70.0 x64
使用者設定檔：全新設定檔
安裝套件：新同文堂 1.5、Tab Mix(勾選自動簡繁轉換) - Rename Tab 1.0.1(預設設定) ，以上即全部。
問題狀況：分頁標題在載入完畢後會恢復為未簡繁轉換前的狀態

以上，謝謝。

**Comment by t7yang** [comment]
了解，如果是套件衝突的話就比較沒辦法，畢竟網頁標題是大家都可以修改的。
