### ISSUE TITLE
Tongwentang not listed in Firefox addons store

### ISSUE THREAD

**Issue by matt-muresan** [softcup/New-Tongwentang-for-Firefox#5]
See 
https://addons.mozilla.org/en-us/android/addon/%E6%96%B0%E5%90%8C%E6%96%87%E5%A0%82-new-tong-wen-tang/

Also not listed if searching.

**Comment by softcup** [comment]
New version but  awaiting review. See

https://addons.mozilla.org/zh-TW/firefox/addon/new_tongwentang/

**Comment by matt-muresan** [comment]
Ah, 謝謝啦
