### ISSUE TITLE
自訂轉換規則

### ISSUE THREAD

**Issue by atx49559** [softcup/New-Tongwentang-for-Firefox#50]
自訂轉換規則似乎只能針對某一個網頁進行設定，而不能套用到整個網域

希望能夠設定為 https://www.google.com/ 時，
以下的頁面都能夠自動套用設定
https://www.google.com/A.html
https://www.google.com/B.html
https://www.google.com/C/A.html
.
.
.

謝謝

Firefox 80.0.1 x64
新同文堂 1.5

**Comment by WhiverFichos** [comment]
你试试写 \*google.com\* 。

**Comment by t7yang** [comment]
目前的規則是用 `*` 號來比對任意字元，所以當你要做到規則模糊比對類似的網址就必須用這種方式。
以維基百科為例，下列的規則就可以做到比對不同的維基網站。
`http*://*wikipedia.org*`
