### ISSUE TITLE
输入区内右击 - 网页：转繁体（或简体），操作结果是输入区

### ISSUE THREAD

**Issue by yfdyh000** [softcup/New-Tongwentang-for-Firefox#8]

**Comment by softcup** [comment]
能麻烦你再详细描述问题吗？
有点不清楚你的问题是什么问题。

**Comment by yfdyh000** [comment]
54.0a2 (2017-03-30) (32 位) 中加载扩展
打开 http://start.firefoxchina.cn/ ，复制 `更多内容请访问` 到网页内的文本框。
文本框右击，网页：转 繁体。结果是文本框内的文本转繁体，而非网页转繁体。简体同上。

**Comment by softcup** [comment]
谢谢，了解。
